### ISSUE TITLE
求整理好之后的代码

### ISSUE THREAD

**Issue by YangQun1** [Lam1360/YOLOv3-model-pruning#14]
你好，感谢你的分享！请问最终整理好的代码什么时候会开放出来呀？现在的代码有好几处报错的地方，好像没法稀疏训练吧？

**Comment by violet17** [comment]
@Lam1360 能把没有整理好的代码prune_util.py发出来参考一下么？谢谢

**Comment by Lam1360** [comment]
是的，目前代码仅仅支持模型的测试。急着要用的话不妨可以试试 yolov3-network-slimming 这个 repo，其中一个 issue 中也提到了它的剪枝效果，貌似也挺好的。
