### ISSUE TITLE
隔壁已经有SlimYOLOv3剪枝版本公开了。。。

### ISSUE THREAD

**Issue by YuGuii** [Lam1360/YOLOv3-model-pruning#29]
你这边的prune_utils.py真的不打算发布吗？？？？怎么感觉你是在骗star，明明都有结果出来了

**Comment by YuGuii** [comment]
https://github.com/PengyiZhang/SlimYOLOv3

**Comment by RizhaoCai** [comment]
隔壁是哪里，求链接

**Comment by lcaikk1314** [comment]
开不开源确实是作者的自由，但是把结果数据全部放出来，而且在公众号专门写一篇关于这code的文章，吸引很多人来，结果大家调完之后发现缺文件，确实浪费大家不少时间，建议作者把这code和对应文章删掉，以免浪费后来人时间

**Comment by YuGuii** [comment]
> 开不开源确实是作者的自由，但是把结果数据全部放出来，而且在公众号专门写一篇关于这code的文章，吸引很多人来，结果大家调完之后发现缺文件，确实浪费大家不少时间，建议作者把这code和对应文章删掉，以免浪费后来人时间

我就是这个意思。。。

**Comment by lz20061213** [comment]
隔壁也没有全发布吧

**Comment by Lam1360** [comment]
@YuGuii ，我在README文档里和 https://github.com/Lam1360/YOLOv3-model-pruning/issues/1#issuecomment-509679904 里面有说过，相关的代码待整理好后再发出来。有结果不一定立刻就可以把代码放出来吧，您提到的SlimYOLOv3我看了一下，他们也有结果了，而且结果更好，是在一个更难的数据集上做的，但是他们也要将代码polish一下再放出来吧。

**Comment by Lam1360** [comment]
@lcaikk1314 ，我是真的冤。。。公众号的文章并不是我写的，我并没有在任何公众号上投过稿，我也没有通过任何渠道宣传过这个repo，公众号的事情说实话我还是过了一段时间之后我才知道的。。。而且，我很早就已经在README文档里面黑体加粗说明了，代码缺少文件目前不能训练。另外，这个repo也是给大家提供一个剪枝的思路，不能保证在任何数据集上都work，这点我也在README里面提到了。

**Comment by YuGuii** [comment]
@Lam1360 对不起，是我理解错了，也没有仔细看readme，我这就把这个issues关了！
