### ISSUE TITLE
How opt.alpha works?

### ISSUE THREAD

**Issue by violet17** [Lam1360/YOLOv3-model-pruning#4]
Hi Lam,
Thank you for the great works.
I haven't found much introductions for alpha. And I have no idea how it works.

requirements:

1. numpy>=1.13
2. tensorboardX
`git clone https://github.com/lanpa/tensorboardX && cd tensorboardX && python setup.py install `
3. albumentations 
 ```
conda install -c conda-forge imgaug
conda install albumentations -c albumentations
```
4. terminaltables
`pip install terminaltables`
5. tqdm
6. torch
7. random
8. matplotlib
9.......

**Comment by Lam1360** [comment]
@violet17, you can refer to this repo [jack-willturner/batchnorm-pruning](https://github.com/jack-willturner/batchnorm-pruning)
