### ISSUE TITLE
请问这个代码实现和您提到的yolov3-network-slimming有啥区别呀

### ISSUE THREAD

**Issue by evercherish** [Lam1360/YOLOv3-model-pruning#5]
您在readme里提到了这项工作：[https://github.com/talebolano/yolov3-network-slimming](url)，思想上应该都是一样的，根据α通道剪枝，代码实现起来有没有啥区别或者改进的地方呀？

**Comment by Lam1360** [comment]
我没仔细看过他的复现，大致实现应该是差不多的
