### ISSUE TITLE
使用 yolo3.weights 训练时报错

### ISSUE THREAD

**Issue by gooseable** [Lam1360/YOLOv3-model-pruning#63]

**Comment by gooseable** [comment]
已经解决了，还是yolo3.weights不完整的问题，重新在官网https://pjreddie.com/media/files/yolov3.weights下载了一次权重文件，大小为248M,不会报这个错误了。

**Comment by gooseable** [comment]
> _No description provided._

**Comment by muyouyang** [comment]
同问,用 yolo3.weights 运行test_prune 文件，模型加载出错
